#pragma once

#define LINE_HEIGHT 10
#define FILES_PER_PAGE 22
#define SELECTOR_SCROLL_DELAY_MS 200
#define MENU_COMBO_DELAY_MS 200

#define SELECTOR_TEXT_COLOR 0xFFFF
#define SELECTOR_HIGHLIGHT_COLOR 0x0F00
#define SELECTOR_BG_COLOR 0x0000

#define SCALE_NUM 5
#define SCALE_DEN 3